#!/bin/sh

#
# Copyright 2025 pyamsoft
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

rm -rf ./*.js || exit 1
tsc "$@" || exit 1
node test.js >>out.temp || exit 1
rm -rf ./*.js || exit 1
mv out.temp out.js || exit 1
exit 0
